### ISSUE TITLE
Not an issue, but instead a thanks

### ISSUE THREAD

**Issue by jdwininger** [lucasmz1/Dolphin_emu_Appimage#1]
thanks so much for building this appimage. I appreciate your effort.

feel free to make this closed.

**Comment by lucasmz1** [comment]
but if you faced the same issue as mine you can use this other build here. it's almost the same thing but it's a dolphin modded.

https://github.com/project-slippi/Ishiiruka/releases/tag/v3.3.1

**Comment by lucasmz1** [comment]
> thanks so much for building this appimage. I appreciate your effort.
> 
> feel free to make this closed.

hello friend. now my dolphin emu build is working fine and well. please enjoy!
