### ISSUE TITLE
Can We Setup Appimage to Use System Theme or At Least Bundle a Dark Theme?

### ISSUE THREAD

**Issue by zicklag** [lucasmz1/Dolphin_emu_Appimage#2]
Hey there! Thanks for this build!

I actually tried this out because the flatpak build of Dolphin has a memory fault when using the Gecko cheat editor and crashes. This build fixes the bug, and gets me a newer version of Dolphin!

My only lack is that the flatpak doesn't read the system theme, or otherwise have a dark theme.

If reading the system theme isn't doable, I'd be happy just to have some dark theme bundled with it if possible. The light theme is just _too_ light! 😎

Maybe this tool can help? https://github.com/linuxdeploy/linuxdeploy-plugin-qt

**Comment by lucasmz1** [comment]
hello my friend... I'll try to see what I can do for you, but I can't promise nothing ok ?

> Hey there! Thanks for this build!
> 
> I actually tried this out because the flatpak build of Dolphin has a memory fault when using the Gecko cheat editor and crashes. This build fixes the bug, and gets me a newer version of Dolphin!
> 
> My only lack is that the flatpak doesn't read the system theme, or otherwise have a dark theme.
> 
> If reading the system theme isn't doable, I'd be happy just to have some dark theme bundled with it if possible. The light theme is just _too_ light! 😎
> 
> Maybe this tool can help? https://github.com/linuxdeploy/linuxdeploy-plugin-qt

**Comment by lucasmz1** [comment]
> Hey there! Thanks for this build!
> 
> I actually tried this out because the flatpak build of Dolphin has a memory fault when using the Gecko cheat editor and crashes. This build fixes the bug, and gets me a newer version of Dolphin!
> 
> My only lack is that the flatpak doesn't read the system theme, or otherwise have a dark theme.
> 
> If reading the system theme isn't doable, I'd be happy just to have some dark theme bundled with it if possible. The light theme is just _too_ light! 😎
> 
> Maybe this tool can help? https://github.com/linuxdeploy/linuxdeploy-plugin-qt

I don't know if it's work but try this: https://github.com/Humanoidear/Lightsout
