### ISSUE TITLE
Appimage do PPSSPP?

### ISSUE THREAD

**Issue by psyalemao** [lucasmz1/Dolphin_emu_Appimage#3]
Cara eai tudo beleza?
Muito legal a sua iniciativa de fornecer AppImage de alguns emuladores e programas. Eu não entendo porque alguns devs nao querem adicionar suporte a appimage, eu particularmente gosto muito de appimage que o aplicativo fica tipo portátil. Sendo assim me pergunto se você não poderia compilar AppImages do PPSSPP? Grato pela atenção.

**Comment by fredy27200** [comment]
that's a very good idea. So I could use it on ES-DE !

**Comment by lucasmz1** [comment]
> Cara eai tudo beleza? Muito legal a sua iniciativa de fornecer AppImage de alguns emuladores e programas. Eu não entendo porque alguns devs nao querem adicionar suporte a appimage, eu particularmente gosto muito de appimage que o aplicativo fica tipo portátil. Sendo assim me pergunto se você não poderia compilar AppImages do PPSSPP? Grato pela atenção.

olá como vai ? então, o ppsspp já é provido pelo quriouspixel no formato appimage, além disso eu só fiz essa build pois a versão que vem no retro-arch tem bugs... o que imposibilita a game-play. infelizmete, eu não tenho muito tempo para poder lidar com builds de outros apps e isso é um problema para mim pois eu gostaria muito. infelizmente vou ficar te devendo.

dê uma olhada nesse link aqui! quem sabe a build desse cara não fucnione para você! 

https://github.com/qurious-pixel/ppsspp/releases/tag/continuous

**Comment by lucasmz1** [comment]
inclusive você pode encontrar o retro-arch no formato appimage com esse core do ppsspp que funciona perfeimtamente!

https://buildbot.libretro.com/nightly/linux/x86_64/

só copiar e colar esse link acima no navegador!

**Comment by lucasmz1** [comment]
Olá, @psyalemao eu fiz um appimage do ppsspp, mas se você quiser posso te passar o arquivo yml dele para você usar com o pkg2appimage assim você pode fazer sua prória build do ppsspp? estou usando um ppa que encotrei na web.

**Comment by lucasmz1** [comment]
qualquer coisa se eu não estiver online você pode me encontrar no telegram por @zainotel

**Comment by lucasmz1** [comment]
@fredy27200 @psyalemao
