### ISSUE TITLE
Controllers/keyboard stop working after changing to another window

### ISSUE THREAD

**Issue by colibris79** [lucasmz1/Dolphin_emu_Appimage#4]
Hi. I am using 5090a02  (25feb) build in my Mint 21.2 (Ubuntu 22.04) machine. 
Everything runs fine till I change to another window (let's say the internet browser) and when I go back to Dolphin's game window the controller and keyboard do not work anymore. I have to close the emulation and start it again. I have tried with 2 controllers (cable and wireless) and it happens the same in both

This issue does not happen in an older appimage that I had here (5.0-15445). Quite old, was still using Qt5

**Comment by lucasmz1** [comment]
@colibris79 are you telling me that your dolphin build on your machine is not working ? what about my appimage ?

**Comment by lucasmz1** [comment]
Indeed you're right about it, even in my appimage it's happening. I believe it's a dolphin issue. I'm afraid I cannot help you. complain in dolphin forum about it. I just pack the app I have not enough knowledge to make changes in the source code.

**Comment by lucasmz1** [comment]
@colibris79 https://forums.dolphin-emu.org/Thread-joystick-not-work-when-window-is-not-active-lost-focus

see this post in the dolphin community, now I'm on the hurry for my work, sorry for don't help you enough!

**Comment by lucasmz1** [comment]
![Captura de tela de 2024-02-28 12-41-56](https://github.com/lucasmz1/Dolphin_emu_Appimage/assets/95252125/30c31738-beb1-48ab-ae94-78513be3795e)

**Comment by colibris79** [comment]
Wow. Completely missed that option (that it was selected in the old one)... That was it!!!
Sorry for bothering with such a simple issue. And thanks for the appimage and the work you put on it. Really convenient!
