### ISSUE TITLE
"Create mappings for other devices" does not stay on after you close dolphin

### ISSUE THREAD

**Issue by colibris79** [lucasmz1/Dolphin_emu_Appimage#5]
I don't know if it is a bug or it's supposed to work like this. But if you activate "Options-Hotkey Settings-Device/Refresh-Create mappings for other devices", the feature will work fine (you can use both keyboard and controller for hotkeys). But if you close Dolphin and you open it again, the option has been deactivated and you have to click on it again. Not a big deal in any case

**Comment by lucasmz1** [comment]
@colibris79 
sorry for my delay!
see if this works for you! that's my best shot.
https://forums.dolphin-emu.org/Thread-unable-to-use-both-controller-and-mouse-for-controls-at-the-same-time

**Comment by colibris79** [comment]
No worries. Thanks for taking the time to answer
It seems that even when the option remains unchecked it usually keeps working. I don't know what happened the first 2 times I tried it. I'll report in case I can reproduce the issue

**Comment by lucasmz1** [comment]
ok, if you got a new issue I'll be glad to help!
