### ISSUE TITLE
auto update doesn't work for me

### ISSUE THREAD

**Issue by ChuckBartowski91** [lucasmz1/Dolphin_emu_Appimage#6]
Hello. I don't know if it's related to the appimage, but when i try to update dolphin at launch this message appears:

`Fetching release information for tag "continuous" from GitHub API.`
`Failed to parse update information: Failed to parse GitHub response: [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - unexpected end of input; expected '[', '{', or a literal`

and update failed appears.

I'm using PCLinuxOS.

**Comment by lucasmz1** [comment]
@ChuckBartowski91 

No it's impossible cause I'm not the dev of the main project if you understand me I'm only a random guy providing an appimage for this app, if you want it updated download a new build that I've made every single time it's being builded.
by the way sorry for my delay in answer you. I don't often reach out github.

**Comment by lucasmz1** [comment]
another thing the devs of this application doesn't know about me, it would be awesome if they could provide an appstream to update automatically this app, but unfortunately they don't.

**Comment by ChuckBartowski91** [comment]
> another thing the devs of this application doesn't know about me, it would be awesome if they could provide an appstream to update automatically this app, but unfortunately they don't.

Understood. So if I'm correct the update available screen is a thing of the emulator thus cannot be deactivated neither.

**Comment by lucasmz1** [comment]
Yes you are right!
